
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author canerkoskos
 */
public class NewJFrame extends javax.swing.JFrame{
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        label1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hizmetno = new javax.swing.JTextField();
        giris = new javax.swing.JButton();
        sifre = new javax.swing.JPasswordField();
        kullanici = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label1.setText("Hizmet no");

        jLabel2.setText("Şifre");

        giris.setText("Giriş");
        giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisActionPerformed(evt);
            }
        });

        kullanici.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Müşteri", "Personel", "Yönetici" }));
        kullanici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hizmetno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(giris, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hizmetno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullanici, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giris, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisActionPerformed
        // TODO add your handling code here:
        //String tck = tckno.getText();
        if(kullanici.getSelectedItem() == "Müşteri"){
        int hizno=Integer.valueOf(hizmetno.getText());
        String parola = new String(sifre.getPassword());
        String message;
        
        Musteri musteri=new Musteri();
        String adsoyad=musteri.getAdSoyad(hizno);
        
        
        if (parola.equals(musteri.getSifre(hizno)) ) {
            
            message = "Hoşgeldiniz, "+adsoyad;
            
        }
       
        else {
            message = "Parola Hatalı";
            
        }
        if (message.equals("Hoşgeldiniz, "+adsoyad)){
            
            
            JOptionPane.showMessageDialog(this, message);
            
            new Islem(hizno).setVisible(true);
           
            this.setVisible(false);
            
        }
        else {
            JOptionPane.showMessageDialog(this, message);
        }
        
        hizmetno.setText("");
        sifre.setText("");
        }
        if(kullanici.getSelectedItem() == "Personel"){
        int id=Integer.valueOf(hizmetno.getText());
        String parola = new String(sifre.getPassword());
        String message;
        
        Personel personel = new Personel();
        String adsoyad=personel.getAdSoyad(id);
        
        
        if (parola.equals(personel.getSifre(id)) ) {
            
            message = "Hoşgeldiniz, "+adsoyad;
            
        }
       
        else {
            message = "Parola Hatalı";
            
        }
        if (message.equals("Hoşgeldiniz, "+adsoyad)){
            
            
            JOptionPane.showMessageDialog(this, message);
            
            new Calisann(id).setVisible(true);
           
            this.setVisible(false);
            
        }
        else {
            JOptionPane.showMessageDialog(this, message);
        }
        
        hizmetno.setText("");
        sifre.setText("");    
        }
        if(kullanici.getSelectedItem() == "Yönetici"){
        int id=Integer.valueOf(hizmetno.getText());
        String parola = new String(sifre.getPassword());
        String message;
        
        Yonetici yonetici=new Yonetici();
        String adsoyad=yonetici.getAdSoyad(id);
        
        
        if (parola.equals(yonetici.getSifre(id)) ) {
            
            message = "Hoşgeldiniz, "+adsoyad;
            
        }
       
        else {
            message = "Parola Hatalı";
            
        }
        if (message.equals("Hoşgeldiniz, "+adsoyad)){
            
            
            JOptionPane.showMessageDialog(this, message);
            
            new Yoneticii(id).setVisible(true);
           
            this.setVisible(false);
            
        }
        else {
            JOptionPane.showMessageDialog(this, message);
        }
        
        hizmetno.setText("");
        sifre.setText("");    
        }
    }//GEN-LAST:event_girisActionPerformed

    private void kullaniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciActionPerformed
        // TODO add your handling code here:
        if(kullanici.getSelectedItem() == "Müşteri"){
            label1.setText("Hizmet no");
        }
        if(kullanici.getSelectedItem() == "Personel"){
            label1.setText("Personel ID");
        }
        if(kullanici.getSelectedItem() == "Yönetici"){
            label1.setText("Yönetici ID");
        }
    }//GEN-LAST:event_kullaniciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton giris;
    private javax.swing.JTextField hizmetno;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> kullanici;
    private javax.swing.JLabel label1;
    private javax.swing.JPasswordField sifre;
    // End of variables declaration//GEN-END:variables
}
