
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author canerkoskos
 */
public class Sifredegistirme extends javax.swing.JFrame {
    int h,a;
    /**
     * Creates new form Sifredegistirme
     */
    public Sifredegistirme() {
        initComponents();
    }
    public Sifredegistirme(int h,int a) {
        initComponents();
        this.h=h;
        this.a=a;
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eskisifre = new javax.swing.JPasswordField();
        yenisifre = new javax.swing.JPasswordField();
        degıstır = new javax.swing.JButton();
        anamenu = new javax.swing.JButton();
        yenisifretekrar = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Eski şifreniz");

        jLabel2.setText("Yeni sifreniz");

        jLabel3.setText("Yeni sifreniz tekrar");

        degıstır.setText("Değiştir");
        degıstır.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degıstırActionPerformed(evt);
            }
        });

        anamenu.setText("Ana menüye dön");
        anamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anamenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(eskisifre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yenisifre)
                                    .addComponent(yenisifretekrar, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(anamenu, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(degıstır, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eskisifre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yenisifre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yenisifretekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(degıstır, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(anamenu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void anamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anamenuActionPerformed
        // TODO add your handling code here:
        if(a==1){
        new Islem(h).setVisible(true);
        this.setVisible(false);
        }
        if(a==2){
        new Calisann(h).setVisible(true);
        this.setVisible(false);
        }
        if(a==3){
        new Yoneticii(h).setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_anamenuActionPerformed

    private void degıstırActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degıstırActionPerformed
        // TODO add your handling code here:
        if(a==1){
        Musteri musteri=new Musteri();
        String eski=new String(eskisifre.getPassword());
        String yeni=new String(yenisifre.getPassword());
        String yenitekrar=new String(yenisifretekrar.getPassword());
        String message;
        if(!eski.equals(musteri.getSifre(h))){
        message="Eski şifreniz yanlış";
        eskisifre.setText("");
        }
        else if(!yeni.equals(yenitekrar)){
        message="Yeni şifreniz tekrarıyla uyuşmuyor";
        yenisifre.setText("");
        yenisifretekrar.setText("");
        }
        else if(musteri.sifredegistirme(h, yeni)==true){
        message="Şifreniz değiştirildi";
        eskisifre.setText("");
        yenisifre.setText("");
        yenisifretekrar.setText("");
        }
        else{
        message="Şifreniz eskisiyle aynı olamaz";
        yenisifre.setText("");
        yenisifretekrar.setText("");
        }
        JOptionPane.showMessageDialog(this, message);
        }
        if(a==2){
        Personel personel=new Personel();
        String eski=new String(eskisifre.getPassword());
        String yeni=new String(yenisifre.getPassword());
        String yenitekrar=new String(yenisifretekrar.getPassword());
        String message;
        if(!eski.equals(personel.getSifre(h))){
        message="Eski şifreniz yanlış";
        eskisifre.setText("");
        }
        else if(!yeni.equals(yenitekrar)){
        message="Yeni şifreniz tekrarıyla uyuşmuyor";
        yenisifre.setText("");
        yenisifretekrar.setText("");
        }
        else if(personel.sifredegistirme(h, yeni)==true){
        message="Şifreniz değiştirildi";
        eskisifre.setText("");
        yenisifre.setText("");
        yenisifretekrar.setText("");
        }
        else{
        message="Şifreniz eskisiyle aynı olamaz";
        yenisifre.setText("");
        yenisifretekrar.setText("");
        }
        JOptionPane.showMessageDialog(this, message);
        }
        if(a==3){
        Yonetici yonetici=new Yonetici();
        String eski=new String(eskisifre.getPassword());
        String yeni=new String(yenisifre.getPassword());
        String yenitekrar=new String(yenisifretekrar.getPassword());
        String message;
        if(!eski.equals(yonetici.getSifre(h))){
        message="Eski şifreniz yanlış";
        eskisifre.setText("");
        }
        else if(!yeni.equals(yenitekrar)){
        message="Yeni şifreniz tekrarıyla uyuşmuyor";
        yenisifre.setText("");
        yenisifretekrar.setText("");
        }
        else if(yonetici.sifredegistirme(h, yeni)==true){
        message="Şifreniz değiştirildi";
        eskisifre.setText("");
        yenisifre.setText("");
        yenisifretekrar.setText("");
        }
        else{
        message="Şifreniz eskisiyle aynı olamaz";
        yenisifre.setText("");
        yenisifretekrar.setText("");
        }
        JOptionPane.showMessageDialog(this, message);
        }  
    }//GEN-LAST:event_degıstırActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sifredegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sifredegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sifredegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sifredegistirme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sifredegistirme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anamenu;
    private javax.swing.JButton degıstır;
    private javax.swing.JPasswordField eskisifre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField yenisifre;
    private javax.swing.JPasswordField yenisifretekrar;
    // End of variables declaration//GEN-END:variables
}
